### PR TITLE
Jest react testing conf

### PR DESCRIPTION
**Pull request by amachad4**
Install jest and react testing library

### CODE REVIEW

**Comment by branmar97** [comment]
Can we set up our unit tests to run pre-push?

**Comment by amachad4** [comment]
> Can we set up our unit tests to run pre-push?

Sure. We should use github actions to run the unit tests in the ci/cd pipeline. I'm not sure if I can do that, see if your able to protect the develop and master branches

**Comment by amachad4** [comment]
I added a workflow to this branch to run the unit tests in the pipeline

**Comment by branmar97** [comment]
> I added a workflow to this branch to run the unit tests in the pipeline

Great stuff!! I'll have to look into how to set up Github actions. Maybe we can look at it together

**Pull request merged**
